(function(){
'use strict';
const VERSION='1.0.0',ROOT_ID='fgo-data-autofill',STATE_KEY='fgo-data-autofill:v1:';
const CLASS_DATA={'セイバー':'剣金.png','アーチャー':'弓金.png','ランサー':'槍金.png','ライダー':'騎金.png','キャスター':'術金.png','アサシン':'殺金.png','バーサーカー':'狂金.png','シールダー':'盾金.png','ルーラー':'裁金.png','アヴェンジャー':'讐金.png','ムーンキャンサー':'月金.png','アルターエゴ':'分金.png','フォーリナー':'降金.png','プリテンダー':'詐金.png','ビースト':'獣金.png'};
const SKILL_MASTER=[{id:'territory-creation-b-plus',name:'陣地作成 B+',icon:'陣地作成.png',flavor:'魔術師として、自らに有利な陣地を作り上げる。\n“工房”と“祭壇”の形成が可能。'}];
const clean=v=>String(v==null?'':v).replace(/\r\n?/g,'\n').trim();
const clone=v=>JSON.parse(JSON.stringify(v));
const esc=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const png=(v,f)=>{const x=clean(v)||f||'';return !x?'':/\.[a-z0-9]+$/i.test(x)?x:x+'.png'};
function inferSkillIcon(name){const x=clean(name).replace(/[【】]/g,'').replace(/\s+(?:EX|[A-E](?:\+\+|\+|-)?|-)$/i,'').trim();return x?x+'.png':'0.png'}
const newSkill=o=>Object.assign({masterId:'',name:'',icon:'',flavor:'',rawWiki:false},o||{});
const newGroup=o=>Object.assign({heading:'',className:'キャスター',classIcon:'術金.png',skills:[newSkill()]},o||{});
function defaultState(){return{defaultClassName:'キャスター',defaultClassIcon:'術金.png',groups:[newGroup({skills:[newSkill({masterId:'territory-creation-b-plus',name:'陣地作成 B+',icon:'陣地作成.png',flavor:SKILL_MASTER[0].flavor})]})],sourceCode:'',outputCode:'',message:''}}
function normalizeState(v){const s=Object.assign(defaultState(),v&&typeof v==='object'?v:{});if(!Array.isArray(s.groups)||!s.groups.length)s.groups=defaultState().groups;s.groups=s.groups.map(g=>{const n=Object.assign(newGroup(),g||{});n.skills=Array.isArray(n.skills)&&n.skills.length?n.skills.map(x=>Object.assign(newSkill(),x||{})):[newSkill()];return n});return s}
function wikiFlavor(v,raw){const x=clean(v);return raw?x:x.replace(/\n/g,'&br()')}
function generateSkillBlock(skill,group){const name=clean(skill.name)||'【スキル名】',icon=png(skill.icon,inferSkillIcon(name)),className=clean(group.className)||'セイバー',classIcon=png(group.classIcon,CLASS_DATA[className]||'0.png');return['|BGCOLOR(#e6e6fa):CENTER:45|BGCOLOR(#f5fffa):LEFT:1000|c','|&ref('+icon+',icon/skill,height=48)|BGCOLOR(#e6e6fa):CENTER:&font(b,110%){'+name+'}&ref('+classIcon+',icon/class,title='+className+',height=25,width=25)|','|~|'+wikiFlavor(skill.flavor,skill.rawWiki)+'|'].join('\n')}
function generateClassSkillBody(groups){const out=[];(groups||[]).forEach(g=>{const list=(g.skills||[]).filter(s=>clean(s.name)||clean(s.icon)||clean(s.flavor));if(!list.length)return;if(clean(g.heading))out.push('***'+clean(g.heading));list.forEach(s=>out.push(generateSkillBlock(s,g)));});return out.join('\n\n')}
function replaceClassSkillSection(source,groups){let text=String(source==null?'':source).replace(/\r\n?/g,'\n'),body=generateClassSkillBody(groups);if(!text.trim())return{text:'**クラススキル\n'+body,replaced:true,message:'元のコードが空欄のため、クラススキル欄だけを生成しました。'};const h=/^\*\*クラススキル[^\n]*$/m.exec(text);if(!h)return{text,replaced:false,message:'「**クラススキル」見出しが見つからなかったため、コードは変更していません。'};const hs=h.index+h[0].length,rs=text[hs]==='\n'?hs+1:hs,rest=text.slice(rs),next=/^\*\*[^*\n][^\n]*$/m.exec(rest);let end=next?rs+next.index:text.length;if(next){const before=rest.slice(0,next.index),re=/^\/\/─┤[^\n]*$/gm;let m,last=null;while((m=re.exec(before)))last=m;if(last)end=rs+last.index}const suffix=text.slice(end).replace(/^\n+/,'');let count=0;(groups||[]).forEach(g=>(g.skills||[]).forEach(s=>{if(clean(s.name)||clean(s.icon)||clean(s.flavor))count++}));return{text:text.slice(0,hs)+'\n'+body+(suffix?'\n\n'+suffix:''),replaced:true,message:'クラススキル欄を反映しました（'+count+'件）。'}}
const core={VERSION,CLASS_DATA,SKILL_MASTER,inferSkillIcon,generateSkillBlock,generateClassSkillBody,replaceClassSkillSection};
if(typeof globalThis!=='undefined')globalThis.FGODataAutofillCore=core;
if(typeof globalThis!=='undefined'&&globalThis.__FGO_DATA_AUTOFILL_TEST__)return;
if(typeof document==='undefined')return;
function style(){if(document.getElementById('fda-style'))return;const e=document.createElement('style');e.id='fda-style';e.textContent=`#${ROOT_ID}{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI","Yu Gothic UI",Meiryo,sans-serif;color:#1f2937;max-width:1180px;margin:16px auto}#${ROOT_ID} *{box-sizing:border-box}.fda{background:#f4f8fc;border:1px solid #b8cee3;border-radius:12px;padding:16px}.fda h2{margin:0 0 5px}.lead,.help{color:#586b7d;line-height:1.6}.sec{background:#fff;border:1px solid #ccd9e5;border-radius:9px;padding:14px;margin:12px 0}.sec h3{margin:0 0 12px;border-left:5px solid #477fad;padding-left:9px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:10px}.field{display:flex;flex-direction:column;gap:4px;font-size:13px;font-weight:600}.wide{grid-column:1/-1}.field input,.field select,.field textarea,.code{width:100%;border:1px solid #aebfd0;border-radius:6px;padding:8px;background:#fff;font:inherit}.field textarea{min-height:90px}.card{border:1px solid #c1d6e7;border-radius:8px;padding:11px;margin:10px 0;background:#f8fbfe}.skill{background:#fff;border:1px solid #d4e0ea;border-radius:7px;padding:10px;margin-top:10px}.head{display:flex;justify-content:space-between;align-items:center;gap:8px}.actions{display:flex;flex-wrap:wrap;gap:7px;margin:10px 0}.btn{border:1px solid #35698f;border-radius:7px;background:#477fad;color:#fff;padding:8px 12px;font-weight:700;cursor:pointer}.sub{background:#fff;color:#35698f}.danger{border-color:#a33;color:#922;background:#fff}.split{display:grid;grid-template-columns:1fr 1fr;gap:12px}.code{min-height:330px;resize:vertical;font-family:Consolas,"BIZ UDGothic",monospace;font-size:12px;line-height:1.45}.msg{padding:9px;border-radius:6px;background:#edf7ed;color:#245c2a}.warn{background:#fff4d6;color:#7a4d00}.check{display:flex;gap:7px;align-items:center;font-size:13px;font-weight:600;margin-top:8px}@media(max-width:700px){.fda{padding:10px}.split{grid-template-columns:1fr}.head{align-items:flex-start;flex-direction:column}}`;document.head.appendChild(e)}
const options=(obj,selected)=>Object.keys(obj).map(k=>'<option value="'+esc(k)+'"'+(k===selected?' selected':'')+'>'+esc(k)+'</option>').join('');
const field=(label,html,wide)=>'<label class="field'+(wide?' wide':'')+'"><span>'+esc(label)+'</span>'+html+'</label>';
const input=(path,value,placeholder)=>'<input data-path="'+path+'" value="'+esc(value)+'" placeholder="'+esc(placeholder||'')+'">';
function groupHtml(g,gi){let h='<div class="card"><div class="head"><strong>形態・グループ '+(gi+1)+'</strong><button type="button" class="btn danger" data-action="delete-group" data-group="'+gi+'">削除</button></div><div class="grid">'+field('見出し',input('groups.'+gi+'.heading',g.heading,'例：〔エイワス〕'))+field('クラス','<select data-class="'+gi+'">'+options(CLASS_DATA,g.className)+'</select>')+field('クラス表記',input('groups.'+gi+'.className',g.className))+field('クラスアイコン',input('groups.'+gi+'.classIcon',g.classIcon))+'</div>';g.skills.forEach((s,si)=>{const masters='<option value="">自由入力</option>'+SKILL_MASTER.map(m=>'<option value="'+m.id+'"'+(m.id===s.masterId?' selected':'')+'>'+esc(m.name)+'</option>').join('');h+='<div class="skill"><div class="head"><strong>クラススキル '+(si+1)+'</strong><button type="button" class="btn danger" data-action="delete-skill" data-group="'+gi+'" data-skill="'+si+'">削除</button></div><div class="grid">'+field('登録済みデータ','<select data-master="'+gi+':'+si+'">'+masters+'</select>')+field('表示名',input('groups.'+gi+'.skills.'+si+'.name',s.name,'陣地作成 B+'))+field('スキルアイコン',input('groups.'+gi+'.skills.'+si+'.icon',s.icon,'陣地作成.png'))+field('フレーバーテキスト','<textarea data-path="groups.'+gi+'.skills.'+si+'.flavor">'+esc(s.flavor)+'</textarea>',true)+'</div><label class="check"><input type="checkbox" data-path="groups.'+gi+'.skills.'+si+'.rawWiki"'+(s.rawWiki?' checked':'')+'>説明欄をWiki記法のまま出力する</label></div>'});return h+'<div class="actions"><button type="button" class="btn sub" data-action="add-skill" data-group="'+gi+'">このグループにスキルを追加</button></div></div>'}
function render(root,s){root.innerHTML='<form class="fda"><h2>FGO データオートフィル</h2><p class="lead">既存のPukiWikiコードを残したまま、クラススキル欄だけを自動反映します。複数形態・形態別クラス・任意数のクラススキルにも対応します。</p><section class="sec"><h3>共通設定</h3><div class="grid">'+field('既定クラス','<select data-default-class>'+options(CLASS_DATA,s.defaultClassName)+'</select>')+field('既定クラス表記',input('defaultClassName',s.defaultClassName))+field('既定クラスアイコン',input('defaultClassIcon',s.defaultClassIcon))+'</div><div class="actions"><button type="button" class="btn sub" data-action="class-all">既定クラスを全グループへ反映</button><button type="button" class="btn sub" data-action="normal">通常例</button><button type="button" class="btn sub" data-action="special">特殊例</button></div></section><section class="sec"><h3>クラススキルデータ</h3>'+s.groups.map(groupHtml).join('')+'<button type="button" class="btn sub" data-action="add-group">形態・グループを追加</button></section><section class="sec"><h3>PukiWikiコードへの反映</h3><p class="help">テンプレート全文または既存ページの編集コードを左欄へ貼り付けてください。`**クラススキル`から次の同階層見出し直前までを置換します。</p><div class="split"><div><b>元のコード</b><textarea class="code" data-path="sourceCode">'+esc(s.sourceCode)+'</textarea></div><div><b>反映後のコード</b><textarea class="code" data-output readonly>'+esc(s.outputCode)+'</textarea></div></div>'+(s.message?'<p class="msg'+(s.message.includes('見つからなかった')?' warn':'')+'">'+esc(s.message)+'</p>':'')+'<div class="actions"><button type="button" class="btn" data-action="apply">クラススキルを反映</button><button type="button" class="btn" data-action="copy-all">反映後コードを一括コピー</button><button type="button" class="btn sub" data-action="copy-section">クラススキル欄だけコピー</button></div></section></form>'}
function getPath(o,p){return p.split('.').reduce((v,k)=>v[k],o)}
function setPath(o,p,v){const a=p.split('.'),last=a.pop(),parent=a.reduce((x,k)=>x[k],o);parent[last]=v}
function copy(text){if(navigator.clipboard&&navigator.clipboard.writeText)return navigator.clipboard.writeText(text);const a=document.createElement('textarea');a.value=text;document.body.appendChild(a);a.select();document.execCommand('copy');a.remove();return Promise.resolve()}
function save(s){try{const x=clone(s);x.outputCode='';x.message='';window.name=STATE_KEY+JSON.stringify(x)}catch(_){}}
function load(){try{return window.name.startsWith(STATE_KEY)?normalizeState(JSON.parse(window.name.slice(STATE_KEY.length))):null}catch(_){return null}}
function sample(special){const s=defaultState();if(special)s.groups=[newGroup({heading:'〔通常〕',className:'キャスター',classIcon:'術金.png',skills:[newSkill({name:'陣地作成 B+',icon:'陣地作成.png',flavor:'通常形態のクラススキル。'}),newSkill({name:'道具作成 A',icon:'道具作成.png',flavor:'通常形態にだけ存在するクラススキル。'})]}),newGroup({heading:'〔特殊形態〕',className:'フォーリナー',classIcon:'降金.png',skills:[newSkill({name:'領域外の生命 EX',icon:'領域外の生命.png',flavor:'特殊形態のクラススキル。'}),newSkill({name:'特殊権能 A',icon:'特殊権能.png',flavor:'&font(b,110%){種別：対宝具　レンジ：1～10　最大補足：100人}&br()',rawWiki:true})]})];return s}
function mount(root){style();let s=load()||defaultState();render(root,s);const redraw=m=>{if(m!=null)s.message=m;render(root,s);save(s)};root.addEventListener('input',e=>{const p=e.target.dataset.path;if(!p)return;setPath(s,p,e.target.type==='checkbox'?e.target.checked:e.target.value);save(s)});root.addEventListener('change',e=>{const t=e.target;if(t.hasAttribute('data-default-class')){s.defaultClassName=t.value;s.defaultClassIcon=CLASS_DATA[t.value];redraw();return}if(t.dataset.class!=null){const g=s.groups[+t.dataset.class];g.className=t.value;g.classIcon=CLASS_DATA[t.value];redraw();return}if(t.dataset.master!=null){const [gi,si]=t.dataset.master.split(':').map(Number),skill=s.groups[gi].skills[si],m=SKILL_MASTER.find(x=>x.id===t.value);skill.masterId=t.value;if(m)Object.assign(skill,{name:m.name,icon:m.icon,flavor:m.flavor,rawWiki:false});redraw()}});root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const a=b.dataset.action,gi=+b.dataset.group,si=+b.dataset.skill;if(a==='add-group')s.groups.push(newGroup({className:s.defaultClassName,classIcon:s.defaultClassIcon}));else if(a==='delete-group'&&s.groups.length>1)s.groups.splice(gi,1);else if(a==='add-skill')s.groups[gi].skills.push(newSkill());else if(a==='delete-skill'&&s.groups[gi].skills.length>1)s.groups[gi].skills.splice(si,1);else if(a==='class-all')s.groups.forEach(g=>{g.className=s.defaultClassName;g.classIcon=s.defaultClassIcon});else if(a==='normal')s=sample(false);else if(a==='special')s=sample(true);else if(a==='apply'){const r=replaceClassSkillSection(s.sourceCode,s.groups);s.outputCode=r.text;s.message=r.message}else if(a==='copy-all'){copy(s.outputCode||replaceClassSkillSection(s.sourceCode,s.groups).text).then(()=>redraw('反映後コードをコピーしました。'));return}else if(a==='copy-section'){copy('**クラススキル\n'+generateClassSkillBody(s.groups)).then(()=>redraw('クラススキル欄をコピーしました。'));return}redraw()})}
function boot(){let root=document.getElementById(ROOT_ID);if(!root){root=document.createElement('div');root.id=ROOT_ID;(document.querySelector('#wikibody,#contents,#content,main')||document.body).appendChild(root)}if(root.dataset.mounted)return;root.dataset.mounted='1';mount(root)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
